Cleanup and bugfixes

diff --git a/scripts/utils/manager-specific/package/dnf b/scripts/utils/manager-specific/package/dnf
--- a/scripts/utils/manager-specific/package/dnf
+++ b/scripts/utils/manager-specific/package/dnf
@@ -41,9 +41,21 @@ function installPackages() {
 if [ "$SEARCH_MODE" = "--executables" ]; then
     MISSING_EXECUTABLES="$(getMissingExecutables "$WANTED_ITEMS")"
     installPackages "$SEARCH_MODE" "$MISSING_EXECUTABLES"
-    echo "Still missing: $(getMissingExecutables "$WANTED_ITEMS")"
+    MISSING_EXECUTABLES="$(getMissingExecutables "$WANTED_ITEMS")"
 elif [ "$SEARCH_MODE" = "--files" ]; then
     MISSING_FILES="$(getMissingFiles "$WANTED_ITEMS")"
     installPackages "$SEARCH_MODE" "$MISSING_FILES"
-    echo "Still missing: $(getMissingFiles "$WANTED_ITEMS")"
+    MISSING_FILES="$(getMissingFiles "$WANTED_ITEMS")"
+else
+    echo "ERROR: Invalid mode or no mode at all was speficied!"
+    exit 1
+fi
+if [ "$MISSING_EXECUTABLES" != "" ]; then
+    echo "ERROR: Still missing package providing the following executables: $MISSING_EXECUTABLES"
+fi
+if [ "$MISSING_FILES" != "" ]; then
+    echo "ERROR: Still missing package providing the following files: $MISSING_FILES"
+fi
+if [ "$MISSING_EXECUTABLES" != "" ] && [ "$MISSING_FILES" != "" ]; then
+    exit 1
 fi
