Fix compatibility check dependency installation

diff --git a/scripts/utils/manager-specific/package/dnf b/scripts/utils/manager-specific/package/dnf
--- a/scripts/utils/manager-specific/package/dnf
+++ b/scripts/utils/manager-specific/package/dnf
@@ -66,5 +66,8 @@ if [ "$COMMAND" = "install" ]; then
     fi
 elif [ "$COMMAND" = "update" ]; then
     updatePackageInfo
+else
+    echo "ERROR: Invalid command"
+    exit 1
 fi
 
